"""empty message

Revision ID: 12c4afa61e4e
Revises: 87bca778d863
Create Date: 2017-12-07 22:23:48.932373

"""

# revision identifiers, used by Alembic.
revision = '12c4afa61e4e'
down_revision = '87bca778d863'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_trend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitter_trend_detail',
    sa.Column('trend_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['twitter_trend.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_trend_detail')
    op.drop_table('twitter_trend')
    ### end Alembic commands ###
