"""empty message

Revision ID: 18c36c482b01
Revises: 12c4afa61e4e
Create Date: 2017-12-12 10:54:53.002094

"""

# revision identifiers, used by Alembic.
revision = '18c36c482b01'
down_revision = '12c4afa61e4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_list_history',
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_published', sa.Integer(), nullable=True),
    sa.Column('open_value', sa.String(), nullable=True),
    sa.Column('high_value', sa.String(), nullable=True),
    sa.Column('low_value', sa.String(), nullable=True),
    sa.Column('close_value', sa.String(), nullable=True),
    sa.Column('adj_close_value', sa.String(), nullable=True),
    sa.Column('volume_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_list_history')
    op.drop_table('stock_list')
    ### end Alembic commands ###
