"""empty message

Revision ID: 87bca778d863
Revises: None
Create Date: 2017-12-04 21:11:53.708218

"""

# revision identifiers, used by Alembic.
revision = '87bca778d863'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('lead', sa.String(), nullable=True),
    sa.Column('src', sa.String(), nullable=True),
    sa.Column('date_created', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.Integer(), nullable=True),
    sa.Column('date_published', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_table('news')
    ### end Alembic commands ###
